const party = [
  // 0
  [
    {
      name: 'Saoirse',
      level: 5,
      job: 'Explorer',
      picture: 'saoirse-full.png',
      team: 'ally',
      vit: 10,
      atk: 10,
      def: 6,
      res: 3,
      spd: 6,
      pool: ['weapon'],
      abilities: [],
      arms: 'shovel',
      armor: 'tunic',
      xp: 0,
    },
    {
      name: 'Parzeval',
      level: 5,
      job: 'Adept',
      picture: 'parzeval-full.png',
      team: 'ally',
      vit: 9,
      atk: 10,
      def: 6,
      res: 6,
      spd: 4,
      pool: ['magic'],
      abilities: [],
      arms: 'stormstaff',
      armor: 'tunic',
      xp: 0,
    },
  ],
  // 1
  [
    {
      name: 'Saoirse',
      level: 5,
      job: 'Explorer',
      picture: 'saoirse-full.png',
      team: 'ally',
      vit: 10,
      atk: 10,
      def: 6,
      res: 3,
      spd: 6,
      pool: ['weapon'],
      abilities: [],
      arms: 'shovel',
      armor: 'tunic',
      xp: 15,
    },
    {
      name: 'Parzeval',
      level: 5,
      job: 'Adept',
      picture: 'parzeval-full.png',
      team: 'ally',
      vit: 9,
      atk: 10,
      def: 6,
      res: 6,
      spd: 4,
      pool: ['magic'],
      abilities: [],
      arms: 'stormstaff',
      armor: 'tunic',
      xp: 15,
      hp: 41
    },
  ]
]