const party = {
  members: [
    {
      name: 'Saoirse',
      picture: 'surtia.jpeg',
      class: 'Fencer',
      mhp: 4,
      attack: 3,
      special: 3,
      defend: 3,
      assist: 3,
      xp: 0,
      arms: {name: 'Estoc', attack: 1},
      armor: {name: 'Doublet', hp: 1},
    },
    {
      name: 'Parzeval',
      picture: 'areval.jpeg',
      class: 'Mage',
      mhp: 4,
      attack: 2,
      special: 4,
      defend: 3,
      assist: 3,
      xp: 0,
      arms: {name: 'Frost Staff', special: 1},
      armor: {name: 'Tunic', hp: 1},
    },
    {
      name: 'Garven',
      picture: 'graven.jpeg',
      class: "Knight",
      mhp: 5,
      attack: 3,
      special: 3,
      defend: 4,
      assist: 3,
      xp: 0,
      arms: {name: 'Steel Sword', attack: 1},
      armor: {name: 'Chainmail', hp: 2},
    },
    {
      name: 'Hanya',
      picture: 'hanya.jpeg',
      class: "Monk",
      mhp: 3,
      attack: 2,
      special: 4,
      defend: 2,
      assist: 5,
      xp: 0,
      arms: {name: 'Baghnakhs', attack: 1, special: 1},
      armor: {name: 'Tunic', hp: 1},
    }    
  ]
};
